### ISSUE TITLE
Where should pre-trained models put

### ISSUE THREAD

**Issue by Haobo-Liu** [Monnte/shape-completion#1]
Hello,Thanks to your excellent work,Could you tell me the project data structure,so I can download pre-trained models and put them to right place.

**Comment by Monnte** [comment]
Hello, you can place the downloaded models anywhere you want. There is a parameter which specify the path to the pre-trained model when running training or inference. 

If you want to continue training for the pre-trained model the `model,opt,ema` all three files are required and also the name of the files should be adjusted in the following way `{name}_000000.{sufix}`, the 000000 represents the current iteration.

If you need any additional help, feel free to ask.

[Link for paper related to this code](https://drive.google.com/file/d/10-bWIvtXW_QMZn2NY1VrrYPnjzi7fgJG/view?usp=sharing)
