### ISSUE TITLE
Dat

### ISSUE THREAD

**Issue by Sakura0124** [Monnte/shape-completion#3]
Thank you very much for your code, it is very helpful to me. However, I encountered problems when training my own dataset.
Below is the error message and the layout of my dataset.
`Arguments: Namespace(batch_size=8, data_path='./datasets/skullfix_dataset/32/', dataset_name='skull_complete', diffusion_steps=1000, dropout=0.0, ema_rate='0.9999', fp16_scale_growth=0.001, in_scale_factor=0, learn_sigma=False, log_dir='logs/train', log_interval=1000, lr=0.0001, lr_anneal_steps=0, microbatch=-1, missing_volumes='0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9', noise_schedule='linear', predict_xstart=False, rescale_learned_sigmas=True, rescale_timesteps=True, resume_checkpoint='', save_interval=10000, schedule_sampler='uniform', sigma_small=False, super_res=False, timestep_respacing='', train_file_path='./datasets/skullfix_dataset/train.txt', use_checkpoint=False, use_fp16=False, use_kl=False, use_roi=False, use_scale_shift_norm=True, val_data_path='', val_ddim=True, val_file_path='./datasets/skullfix_dataset/val.txt', val_interval=10000, weight_decay=0.0)
creating model and diffusion...
Model Parameters:
            in_channels: 1
            out_channels: 1
            cond_in_channels: 1
            dropout: 0.0
            conv_resample: True
            use_checkpoint: False
            num_heads: 1
            use_scale_shift_norm: True
            attention_resolutions: []
            in_scale_factor: 0
            channel_mult: (2, 4, 4, 4)
            num_res_blocks: 3
            model_channels: 32
        
creating data loader...
Loading data from ./datasets/skullfix_dataset/32/ and filtering with ./datasets/skullfix_dataset/val.txt
Missing counterpats: 0
Final dataset size: 25
training...
Loading data from ./datasets/skullfix_dataset/32/ and filtering with ./datasets/skullfix_dataset/train.txt
Missing counterpats: 0
Final dataset size: 75
running validation...
Traceback (most recent call last):
...
...
RuntimeError: Given groups=1, weight of size [32, 1, 3, 3, 3], expected input[8, 2, 32, 32, 32] to have 1 channels, but got 2 channels instead`
![image](https://github.com/user-attachments/assets/b5e9153a-f2bd-4704-a5eb-b0102578047c)
I don’t know if you have encountered similar problems. Thanks again @Monnte

**Comment by Monnte** [comment]
Hi looks like that your dataset you have implemented creates a 2 channnels input and by default network expect the input to have 1 channel. So just change the input layer for the network. If you need further help you can contact me on different platform (e.g. Discord, my nick is: monnte). :+1:

**Comment by Sakura0124** [comment]
Thanks for your reply! Do you mean the number of channels in DiffComplete? I tried to change the in_channels, but it still gave an error.
I don't know if there was a problem when I was processing the dataset.

**Comment by Sakura0124** [comment]
![image](https://github.com/user-attachments/assets/6166f780-2a81-43f1-a558-10c3546334db)

**Comment by Monnte** [comment]
Try to change the `cond_in_channels=2`.

**Comment by Sakura0124** [comment]
Thanks for your help, I changed some code which caused this error and now I have fixed it. Thanks again for your code.
